In [1]:
with open("alpaca_hindi_sft_clean.jsonl", "r", encoding="utf-8") as f:
    for i in range(1,2):
        print(f.readline().strip())

{"text": "### प्रश्न:\nस्वस्थ रहने के लिए तीन सुझाव दें।\n\n### उत्तर:\n1. संतुलित और पौष्टिक आहार लेंः सुनिश्चित करें कि आपके भोजन में विभिन्न प्रकार के फल और सब्जियां, दुबला प्रोटीन, साबुत अनाज और स्वस्थ वसा शामिल हों। यह आपके शरीर को सर्वोत्तम रूप से कार्य करने के लिए आवश्यक पोषक तत्व प्रदान करने में मदद करता है और पुरानी बीमारियों को रोकने में मदद कर सकता है।\n\n2. नियमित शारीरिक गतिविधि में संलग्न रहेंः मजबूत हड्डियों, मांसपेशियों और हृदय स्वास्थ्य को बनाए रखने के लिए व्यायाम महत्वपूर्ण है। प्रत्येक सप्ताह कम से कम 150 मिनट के मध्यम एरोबिक व्यायाम या 75 मिनट के जोरदार व्यायाम का लक्ष्य रखें।\n\n3. पर्याप्त नींद लेंः पर्याप्त गुणवत्ता वाली नींद लेना शारीरिक और मानसिक कल्याण के लिए महत्वपूर्ण है। यह मनोदशा को नियंत्रित करने, संज्ञानात्मक कार्य में सुधार करने और स्वस्थ विकास और प्रतिरक्षा कार्य का समर्थन करने में मदद करता है। हर रात 7 से 9 घंटे सोने का लक्ष्य रखें।"}


In [2]:
with open("alpaca_hindi_sft_clean.jsonl", "r", encoding="utf-8") as f:
    lines = f.readlines()

print("Second line:", lines[1].strip())


Second line: {"text": "### प्रश्न:\nतीन प्राथमिक रंग कौन से हैं?\n\n### उत्तर:\nतीन प्राथमिक रंग लाल, नीला और पीला हैं। इन रंगों को प्राथमिक कहा जाता है क्योंकि इन्हें अन्य रंगों को मिलाकर नहीं बनाया जा सकता है और अन्य सभी रंगों को विभिन्न अनुपातों में मिलाकर बनाया जा सकता है। प्रकाश के लिए उपयोग की जाने वाली योगात्मक रंग प्रणाली में, प्राथमिक रंग लाल, हरा और नीला (आर. जी. बी.) हैं।"}


In [3]:
print("Third line:", lines[3].strip())

Third line: {"text": "### प्रश्न:\nहम वायु प्रदूषण को कैसे कम कर सकते हैं?\n\n### उत्तर:\nवायु प्रदूषण को कम करने के कई तरीके हैं, जिनमें शामिल हैंः\n\n1. ऊर्जा की खपत को कम करनाः ऊर्जा की बचत करके हम बिजली संयंत्रों से उत्सर्जित प्रदूषण की मात्रा को कम करते हैं। इसे प्राप्त करने के कुछ तरीकों में शामिल हैंः ऊर्जा-कुशल उपकरणों और प्रकाश का उपयोग करना, घरों को इन्सुलेट करना और उपयोग में नहीं होने पर रोशनी और इलेक्ट्रॉनिक्स को बंद करना।\n\n2. सार्वजनिक परिवहन या कारपूल का उपयोगः कार और ट्रक प्रदूषण के प्रमुख स्रोत हैं। सार्वजनिक परिवहन, कारपूलिंग या बाइकिंग का उपयोग करके, आप सड़क पर कारों की संख्या को कम कर सकते हैं, जो बदले में उत्सर्जन को कम करता है।\n\n3. अपशिष्ट के लिए जिम्मेदार बनेंः जब अपशिष्ट को जलाया या विघटित किया जाता है, तो वे हवा में हानिकारक गैसों को छोड़ सकते हैं। खतरनाक कचरे का सही तरीके से निपटान करें और जब भी संभव हो प्लास्टिक, कागज और कांच जैसी सामग्री का पुनर्चक्रण करें।\n\n4. स्वच्छ ऊर्जा स्रोतों का समर्थनः सौर और पवन ऊर्जा जैसे नवीकरणीय ऊर्जा स्रोत बहुत कम या कोई प्र

In [4]:
lines[3].strip()

'{"text": "### प्रश्न:\\nहम वायु प्रदूषण को कैसे कम कर सकते हैं?\\n\\n### उत्तर:\\nवायु प्रदूषण को कम करने के कई तरीके हैं, जिनमें शामिल हैंः\\n\\n1. ऊर्जा की खपत को कम करनाः ऊर्जा की बचत करके हम बिजली संयंत्रों से उत्सर्जित प्रदूषण की मात्रा को कम करते हैं। इसे प्राप्त करने के कुछ तरीकों में शामिल हैंः ऊर्जा-कुशल उपकरणों और प्रकाश का उपयोग करना, घरों को इन्सुलेट करना और उपयोग में नहीं होने पर रोशनी और इलेक्ट्रॉनिक्स को बंद करना।\\n\\n2. सार्वजनिक परिवहन या कारपूल का उपयोगः कार और ट्रक प्रदूषण के प्रमुख स्रोत हैं। सार्वजनिक परिवहन, कारपूलिंग या बाइकिंग का उपयोग करके, आप सड़क पर कारों की संख्या को कम कर सकते हैं, जो बदले में उत्सर्जन को कम करता है।\\n\\n3. अपशिष्ट के लिए जिम्मेदार बनेंः जब अपशिष्ट को जलाया या विघटित किया जाता है, तो वे हवा में हानिकारक गैसों को छोड़ सकते हैं। खतरनाक कचरे का सही तरीके से निपटान करें और जब भी संभव हो प्लास्टिक, कागज और कांच जैसी सामग्री का पुनर्चक्रण करें।\\n\\n4. स्वच्छ ऊर्जा स्रोतों का समर्थनः सौर और पवन ऊर्जा जैसे नवीकरणीय ऊर्जा स्रोत बहुत कम या कोई प्

In [5]:
import json
obj = json.loads(lines[1])

In [6]:
obj

{'text': '### प्रश्न:\nतीन प्राथमिक रंग कौन से हैं?\n\n### उत्तर:\nतीन प्राथमिक रंग लाल, नीला और पीला हैं। इन रंगों को प्राथमिक कहा जाता है क्योंकि इन्हें अन्य रंगों को मिलाकर नहीं बनाया जा सकता है और अन्य सभी रंगों को विभिन्न अनुपातों में मिलाकर बनाया जा सकता है। प्रकाश के लिए उपयोग की जाने वाली योगात्मक रंग प्रणाली में, प्राथमिक रंग लाल, हरा और नीला (आर. जी. बी.) हैं।'}

In [7]:
obj["text"]

'### प्रश्न:\nतीन प्राथमिक रंग कौन से हैं?\n\n### उत्तर:\nतीन प्राथमिक रंग लाल, नीला और पीला हैं। इन रंगों को प्राथमिक कहा जाता है क्योंकि इन्हें अन्य रंगों को मिलाकर नहीं बनाया जा सकता है और अन्य सभी रंगों को विभिन्न अनुपातों में मिलाकर बनाया जा सकता है। प्रकाश के लिए उपयोग की जाने वाली योगात्मक रंग प्रणाली में, प्राथमिक रंग लाल, हरा और नीला (आर. जी. बी.) हैं।'

In [8]:
q, a = obj["text"].split("### उत्तर:\n")

In [9]:
q

'### प्रश्न:\nतीन प्राथमिक रंग कौन से हैं?\n\n'

In [10]:
a

'तीन प्राथमिक रंग लाल, नीला और पीला हैं। इन रंगों को प्राथमिक कहा जाता है क्योंकि इन्हें अन्य रंगों को मिलाकर नहीं बनाया जा सकता है और अन्य सभी रंगों को विभिन्न अनुपातों में मिलाकर बनाया जा सकता है। प्रकाश के लिए उपयोग की जाने वाली योगात्मक रंग प्रणाली में, प्राथमिक रंग लाल, हरा और नीला (आर. जी. बी.) हैं।'

In [11]:
file_path = "alpaca_hindi_sft_clean.jsonl"

good = 0
bad = 0
sample_examples = []

with open(file_path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, 1):
        line = line.strip()
        if not line:
            bad += 1
            continue

In [12]:
bad

0

In [13]:
try:
    data = json.loads(line)
    text = data.get("text", "").strip()
    if text and len(text) > 30:  # kam se kam meaningful length
        good += 1
        if good <= 5:  # pehle 5 sahi examples dikha
            sample_examples.append(text)
        else:
            bad += 1
except json.JSONDecodeError as e:
    print(f"Line {i} JSON error: {e}")
    bad += 1
except Exception as e:
    print(f"Line {i} error: {e}")
    bad += 1

In [14]:
bad

0

In [15]:
good

1

In [16]:
sample_examples

['### प्रश्न:\nदिए गए कानूनी दस्तावेज़ का विश्लेषण करें और मुख्य बिंदुओं की व्याख्या करें।\nनिम्नलिखित दो पक्षों के बीच एक अनुबंध का एक अंश है, जिसे "कंपनी ए" और "कंपनी बी" लेबल किया गया हैः\n\n"कंपनी ए कंपनी बी को प्रदान किए गए वित्तीय विवरणों की सटीकता सुनिश्चित करने में उचित सहायता प्रदान करने के लिए सहमत है। इसमें कंपनी ए को कर्मचारियों और अन्य दस्तावेजों तक उचित पहुंच की अनुमति देना शामिल है जो कंपनी बी की समीक्षा के लिए आवश्यक हो सकते हैं। कंपनी बी कंपनी ए द्वारा प्रदान किए गए दस्तावेज़ को विश्वास में रखने के लिए सहमत है, और कंपनी ए की स्पष्ट अनुमति के बिना किसी भी तीसरे पक्ष को जानकारी का खुलासा नहीं करेगी। "\n\n### उत्तर:\nकंपनी ए और कंपनी बी के बीच अनुबंध दोनों पक्षों के बीच एक समझ को रेखांकित करता है, जिसके तहत कंपनी ए कंपनी बी द्वारा प्रदान किए गए वित्तीय विवरणों की सटीकता सुनिश्चित करने में सहायता प्रदान करने के लिए सहमत होती है। इस सहायता में कंपनी बी द्वारा आवश्यक समझे जाने वाले कर्मियों और महत्वपूर्ण दस्तावेजों तक पहुंच प्रदान करना शामिल हो सकता है। बदले में, कंपनी बी कं

In [17]:
import json

file_path = "alpaca_hindi_sft_clean.jsonl"

good = 0
bad = 0
sample_examples = []

with open(file_path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, 1):
        line = line.strip()
        if not line:
            bad += 1
            continue
        try:
            data = json.loads(line)
            text = data.get("text", "").strip()
            if text and len(text) > 30:  # kam se kam meaningful length
                good += 1
                if good <= 5:  # pehle 5 sahi examples dikha
                    sample_examples.append(text)
            else:
                bad += 1
        except json.JSONDecodeError as e:
            print(f"Line {i} JSON error: {e}")
            bad += 1
        except Exception as e:
            print(f"Line {i} error: {e}")
            bad += 1

print(f"\nTotal lines processed: {good + bad}")
print(f"Good (valid) examples: {good}")
print(f"Bad/Empty/Invalid: {bad}")
print(f"Valid percentage: {good / (good + bad) * 100:.2f}%")

print("\nFirst 5 good examples:")
for ex in sample_examples:
    print("\n" + "-"*80)
    print(ex[:500] + "..." if len(ex) > 500 else ex)


Total lines processed: 36353
Good (valid) examples: 36353
Bad/Empty/Invalid: 0
Valid percentage: 100.00%

First 5 good examples:

--------------------------------------------------------------------------------
### प्रश्न:
स्वस्थ रहने के लिए तीन सुझाव दें।

### उत्तर:
1. संतुलित और पौष्टिक आहार लेंः सुनिश्चित करें कि आपके भोजन में विभिन्न प्रकार के फल और सब्जियां, दुबला प्रोटीन, साबुत अनाज और स्वस्थ वसा शामिल हों। यह आपके शरीर को सर्वोत्तम रूप से कार्य करने के लिए आवश्यक पोषक तत्व प्रदान करने में मदद करता है और पुरानी बीमारियों को रोकने में मदद कर सकता है।

2. नियमित शारीरिक गतिविधि में संलग्न रहेंः मजबूत हड्डियों, मांसपेशियों और हृदय स्वास्थ्य को बनाए रखने के लिए व्यायाम महत्वपूर्ण है। प्रत्येक सप्ताह...

--------------------------------------------------------------------------------
### प्रश्न:
तीन प्राथमिक रंग कौन से हैं?

### उत्तर:
तीन प्राथमिक रंग लाल, नीला और पीला हैं। इन रंगों को प्राथमिक कहा जाता है क्योंकि इन्हें अन्य रंगों को मिलाकर नहीं बनाया जा सकता है और अन्य सभी रंगों 

In [18]:
import json
with open("alpaca_hindi_sft_clean.jsonl", "r", encoding="utf-8") as f:
    line = f.readline()
    obj = json.loads(line)

    text = obj.get("text", "").strip()
    print(text)

    

### प्रश्न:
स्वस्थ रहने के लिए तीन सुझाव दें।

### उत्तर:
1. संतुलित और पौष्टिक आहार लेंः सुनिश्चित करें कि आपके भोजन में विभिन्न प्रकार के फल और सब्जियां, दुबला प्रोटीन, साबुत अनाज और स्वस्थ वसा शामिल हों। यह आपके शरीर को सर्वोत्तम रूप से कार्य करने के लिए आवश्यक पोषक तत्व प्रदान करने में मदद करता है और पुरानी बीमारियों को रोकने में मदद कर सकता है।

2. नियमित शारीरिक गतिविधि में संलग्न रहेंः मजबूत हड्डियों, मांसपेशियों और हृदय स्वास्थ्य को बनाए रखने के लिए व्यायाम महत्वपूर्ण है। प्रत्येक सप्ताह कम से कम 150 मिनट के मध्यम एरोबिक व्यायाम या 75 मिनट के जोरदार व्यायाम का लक्ष्य रखें।

3. पर्याप्त नींद लेंः पर्याप्त गुणवत्ता वाली नींद लेना शारीरिक और मानसिक कल्याण के लिए महत्वपूर्ण है। यह मनोदशा को नियंत्रित करने, संज्ञानात्मक कार्य में सुधार करने और स्वस्थ विकास और प्रतिरक्षा कार्य का समर्थन करने में मदद करता है। हर रात 7 से 9 घंटे सोने का लक्ष्य रखें।


In [19]:
len(data)

1

In [20]:
data = []
skipped = 0

jsonl_file = "alpaca_hindi_sft_clean.jsonl"

with open(jsonl_file, "r", encoding="utf-8") as f:
    for line_num, line in enumerate(f, 1):
        line = line.strip()
        if not line:
            skipped += 1
            continue
            
        try:
            entry = json.loads(line)
            text = entry.get("text", "").strip()
            
            if not text or len(text) < 30:
                skipped += 1
                continue
                
            data.append(text)

        except Exception as e:
            print(f"Line {line_num} skipped: {e}")
            skipped += 1

print(f"Loaded {len(data)} valid examples | Skipped: {skipped}")
if len(data) == 0:
    raise ValueError("No valid data!")


Loaded 36353 valid examples | Skipped: 0


In [21]:
len(data)

36353

In [22]:
text = data[3]
text

'### प्रश्न:\nहम वायु प्रदूषण को कैसे कम कर सकते हैं?\n\n### उत्तर:\nवायु प्रदूषण को कम करने के कई तरीके हैं, जिनमें शामिल हैंः\n\n1. ऊर्जा की खपत को कम करनाः ऊर्जा की बचत करके हम बिजली संयंत्रों से उत्सर्जित प्रदूषण की मात्रा को कम करते हैं। इसे प्राप्त करने के कुछ तरीकों में शामिल हैंः ऊर्जा-कुशल उपकरणों और प्रकाश का उपयोग करना, घरों को इन्सुलेट करना और उपयोग में नहीं होने पर रोशनी और इलेक्ट्रॉनिक्स को बंद करना।\n\n2. सार्वजनिक परिवहन या कारपूल का उपयोगः कार और ट्रक प्रदूषण के प्रमुख स्रोत हैं। सार्वजनिक परिवहन, कारपूलिंग या बाइकिंग का उपयोग करके, आप सड़क पर कारों की संख्या को कम कर सकते हैं, जो बदले में उत्सर्जन को कम करता है।\n\n3. अपशिष्ट के लिए जिम्मेदार बनेंः जब अपशिष्ट को जलाया या विघटित किया जाता है, तो वे हवा में हानिकारक गैसों को छोड़ सकते हैं। खतरनाक कचरे का सही तरीके से निपटान करें और जब भी संभव हो प्लास्टिक, कागज और कांच जैसी सामग्री का पुनर्चक्रण करें।\n\n4. स्वच्छ ऊर्जा स्रोतों का समर्थनः सौर और पवन ऊर्जा जैसे नवीकरणीय ऊर्जा स्रोत बहुत कम या कोई प्रदूषण उत्पन्न नहीं करत

In [23]:
text1 = data[32352]
text1

'### प्रश्न:\nकोरस के साथ चार पंक्तियों में एक गीत लिखें।\n\n### उत्तर:\nआयत 1:\nमेरी खिड़की पर बारिश की बूंदें, मैं बाहर देख रहा हूँ,\nदुनिया धूसर लगती है, खुशी मुझे नहीं मिलती,\nलेकिन फिर मैं आपका चेहरा देखता हूँ, वह मुस्कान इतनी उज्ज्वल है,\nयह एक तूफानी रात के बाद एक धूप वाले दिन की तरह है।\n\nकोरसः\nतुम मेरी दुनिया को रोशन करते हो, बादलों को दूर भगाते हो,\nतुम सब कुछ ठीक करते हो, तुम्हारे प्यार में मैं मंत्रमुग्ध हूँ\n\nआयत 2:\nदिन खराब और कठिन था, मैं बहुत उदास महसूस कर रहा हूँ,\nदुनिया का वजन, ऐसा लगता है जैसे मैं डूब सकता हूँ,\nलेकिन फिर आप मेरा हाथ पकड़ते हैं, आपका स्पर्श प्रज्वलित हो जाता है,\nआप मुझे एक ऐसी दुनिया में ले जाते हैं जहाँ सब कुछ उज्ज्वल है।\n\n(कोरस)\nतुम मेरी दुनिया को रोशन करते हो, बादलों को दूर भगाते हो,\nतुम सब कुछ ठीक करते हो, तुम्हारे प्यार में मैं मंत्रमुग्ध हूँ\n\nआयत 3:\nकभी-कभी जीवन मुझे अज्ञात स्थानों पर ले जाता है,\nजहाँ सब कुछ अंधेरा है, और मैं अकेला हूँ,\nलेकिन आप मेरे मार्गदर्शक प्रकाश हैं, आप मुझे रास्ता दिखाते हैं,\nतुम मेरे साथ हो तो सब कुछ ठीक

In [24]:
# tokenize full text
import sentencepiece as spm

# Load tokenizer
tokenizer = spm.SentencePieceProcessor()
tokenizer.load("hindi_tokenizer_new.model")

full_ids = tokenizer.encode(text)
full_ids

[28843,
 1,
 2821,
 28911,
 1,
 3623,
 3727,
 4019,
 28,
 1148,
 253,
 36,
 422,
 61,
 28910,
 1,
 832,
 28911,
 1,
 7692,
 4019,
 28,
 253,
 140,
 11,
 349,
 1880,
 61,
 28879,
 2990,
 679,
 61,
 28920,
 1,
 28924,
 28889,
 2895,
 26,
 9272,
 28,
 253,
 431,
 28920,
 2895,
 26,
 6940,
 1007,
 153,
 1511,
 23407,
 32,
 346,
 19498,
 4019,
 26,
 2362,
 28,
 253,
 302,
 61,
 28869,
 695,
 973,
 140,
 11,
 256,
 7272,
 22,
 679,
 61,
 28920,
 2895,
 28893,
 22362,
 7099,
 44,
 1488,
 40,
 1055,
 431,
 28879,
 3042,
 28,
 16681,
 28867,
 2364,
 431,
 44,
 1055,
 22,
 100,
 280,
 46,
 6024,
 44,
 13715,
 28,
 853,
 431,
 28869,
 1,
 28932,
 28889,
 3086,
 4285,
 158,
 135,
 28500,
 40,
 1055,
 28920,
 135,
 44,
 3714,
 4019,
 11,
 1237,
 6359,
 61,
 28869,
 3086,
 4285,
 28879,
 135,
 28500,
 299,
 158,
 6658,
 1697,
 40,
 1055,
 1007,
 28879,
 125,
 1508,
 46,
 8367,
 26,
 1032,
 28,
 253,
 36,
 422,
 61,
 28879,
 176,
 4287,
 22,
 14286,
 28,
 253,
 629,
 15,
 28869,
 1,
 28937,
 28889,
 

In [25]:
max_len=512
full_ids[:max_len]

[28843,
 1,
 2821,
 28911,
 1,
 3623,
 3727,
 4019,
 28,
 1148,
 253,
 36,
 422,
 61,
 28910,
 1,
 832,
 28911,
 1,
 7692,
 4019,
 28,
 253,
 140,
 11,
 349,
 1880,
 61,
 28879,
 2990,
 679,
 61,
 28920,
 1,
 28924,
 28889,
 2895,
 26,
 9272,
 28,
 253,
 431,
 28920,
 2895,
 26,
 6940,
 1007,
 153,
 1511,
 23407,
 32,
 346,
 19498,
 4019,
 26,
 2362,
 28,
 253,
 302,
 61,
 28869,
 695,
 973,
 140,
 11,
 256,
 7272,
 22,
 679,
 61,
 28920,
 2895,
 28893,
 22362,
 7099,
 44,
 1488,
 40,
 1055,
 431,
 28879,
 3042,
 28,
 16681,
 28867,
 2364,
 431,
 44,
 1055,
 22,
 100,
 280,
 46,
 6024,
 44,
 13715,
 28,
 853,
 431,
 28869,
 1,
 28932,
 28889,
 3086,
 4285,
 158,
 135,
 28500,
 40,
 1055,
 28920,
 135,
 44,
 3714,
 4019,
 11,
 1237,
 6359,
 61,
 28869,
 3086,
 4285,
 28879,
 135,
 28500,
 299,
 158,
 6658,
 1697,
 40,
 1055,
 1007,
 28879,
 125,
 1508,
 46,
 8367,
 26,
 1032,
 28,
 253,
 36,
 422,
 61,
 28879,
 176,
 4287,
 22,
 14286,
 28,
 253,
 629,
 15,
 28869,
 1,
 28937,
 28889,
 

In [26]:
len(full_ids[:max_len]), len(full_ids)

(369, 369)

In [27]:
max_len=512
if len(full_ids) > max_len:
    full_ids = full_ids[:max_len]

In [29]:
import torch
input_ids = torch.tensor(full_ids, dtype=torch.long)
input_ids

tensor([28843,     1,  2821, 28911,     1,  3623,  3727,  4019,    28,  1148,
          253,    36,   422,    61, 28910,     1,   832, 28911,     1,  7692,
         4019,    28,   253,   140,    11,   349,  1880,    61, 28879,  2990,
          679,    61, 28920,     1, 28924, 28889,  2895,    26,  9272,    28,
          253,   431, 28920,  2895,    26,  6940,  1007,   153,  1511, 23407,
           32,   346, 19498,  4019,    26,  2362,    28,   253,   302,    61,
        28869,   695,   973,   140,    11,   256,  7272,    22,   679,    61,
        28920,  2895, 28893, 22362,  7099,    44,  1488,    40,  1055,   431,
        28879,  3042,    28, 16681, 28867,  2364,   431,    44,  1055,    22,
          100,   280,    46,  6024,    44, 13715,    28,   853,   431, 28869,
            1, 28932, 28889,  3086,  4285,   158,   135, 28500,    40,  1055,
        28920,   135,    44,  3714,  4019,    11,  1237,  6359,    61, 28869,
         3086,  4285, 28879,   135, 28500,   299,   158,  6658, 

In [30]:
prompt_end_pos = text.rfind("उत्तर:")
prompt_end_pos

57

In [31]:
len("उत्तर:")

6

In [32]:
text[:prompt_end_pos]

'### प्रश्न:\nहम वायु प्रदूषण को कैसे कम कर सकते हैं?\n\n### '

In [33]:
prompt_text = text[:prompt_end_pos + len("उत्तर:")]
prompt_text

'### प्रश्न:\nहम वायु प्रदूषण को कैसे कम कर सकते हैं?\n\n### उत्तर:'

In [34]:
tokenizer.encode(prompt_text)

[28843,
 1,
 2821,
 28911,
 1,
 3623,
 3727,
 4019,
 28,
 1148,
 253,
 36,
 422,
 61,
 28910,
 1,
 832,
 28911]

In [35]:
len(tokenizer.encode(prompt_text))

18

In [36]:
prompt_text_len = len(tokenizer.encode(prompt_text))
prompt_text_len

18

In [37]:
# prompt_token_len = int(len(full_ids) * 0.7)
# prompt_token_len

In [38]:
labels = input_ids.clone()
labels

tensor([28843,     1,  2821, 28911,     1,  3623,  3727,  4019,    28,  1148,
          253,    36,   422,    61, 28910,     1,   832, 28911,     1,  7692,
         4019,    28,   253,   140,    11,   349,  1880,    61, 28879,  2990,
          679,    61, 28920,     1, 28924, 28889,  2895,    26,  9272,    28,
          253,   431, 28920,  2895,    26,  6940,  1007,   153,  1511, 23407,
           32,   346, 19498,  4019,    26,  2362,    28,   253,   302,    61,
        28869,   695,   973,   140,    11,   256,  7272,    22,   679,    61,
        28920,  2895, 28893, 22362,  7099,    44,  1488,    40,  1055,   431,
        28879,  3042,    28, 16681, 28867,  2364,   431,    44,  1055,    22,
          100,   280,    46,  6024,    44, 13715,    28,   853,   431, 28869,
            1, 28932, 28889,  3086,  4285,   158,   135, 28500,    40,  1055,
        28920,   135,    44,  3714,  4019,    11,  1237,  6359,    61, 28869,
         3086,  4285, 28879,   135, 28500,   299,   158,  6658, 

In [39]:
labels[:prompt_text_len]

tensor([28843,     1,  2821, 28911,     1,  3623,  3727,  4019,    28,  1148,
          253,    36,   422,    61, 28910,     1,   832, 28911])

In [40]:
labels[:prompt_text_len] = -100
labels

tensor([ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,     1,  7692,
         4019,    28,   253,   140,    11,   349,  1880,    61, 28879,  2990,
          679,    61, 28920,     1, 28924, 28889,  2895,    26,  9272,    28,
          253,   431, 28920,  2895,    26,  6940,  1007,   153,  1511, 23407,
           32,   346, 19498,  4019,    26,  2362,    28,   253,   302,    61,
        28869,   695,   973,   140,    11,   256,  7272,    22,   679,    61,
        28920,  2895, 28893, 22362,  7099,    44,  1488,    40,  1055,   431,
        28879,  3042,    28, 16681, 28867,  2364,   431,    44,  1055,    22,
          100,   280,    46,  6024,    44, 13715,    28,   853,   431, 28869,
            1, 28932, 28889,  3086,  4285,   158,   135, 28500,    40,  1055,
        28920,   135,    44,  3714,  4019,    11,  1237,  6359,    61, 28869,
         3086,  4285, 28879,   135, 28500,   299,   158,  6658, 

In [41]:
from torch.utils.data import Dataset
import torch
import json

In [42]:
class HindiSFT_dataset(Dataset):
    def __init__(self, jsonl_file, tokeninzer, max_len=512):
        """
        Full SFT ke liye optimized loader.
        - Every line: {"text": "### प्रश्न:\n...\n### उत्तर:\n..."}
        - Answer-only loss: prompt part ignore (-100)
        """

        self.tokenizer = tokenizer
        self.max_len = max_len
        self.data = []
        skipped = 0

        print(f"Loading dataset: {jsonl_file}")

        with open(jsonl_file, "r", encoding="utf-8") as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    skipped += 1
                    continue

                try:
                    entry = json.loads(line)
                    text = entry.get("text", "").strip()

                    if not text or len(text) < 30:
                        skipped += 1
                        continue

                    self.data.append(text)

                except Exception as e:
                    print(f"Line {line_num} skipped: {e}")
                    skipped += 1

        print(f"Loaded {len(self.data)} valid examples | Skipped: {skipped}")
        if len(self.data) == 0:
            raise ValueError("No valid data!")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        text = self.data[idx]

        # tokenize full text
        full_ids = self.tokenizer.encode(text)

        if len(full_ids) > self.max_len:
            full_ids = full_ids[:self.max_len]

        input_ids = torch.tensor(full_ids, dtype=torch.long)

        #Answer only loss only after उत्तर:
        prompt_end_pos = text.rfind("उत्तर:")

        if prompt_end_pos != -1:
            prompt_text = text[:prompt_end_pos + len("उत्तर:")]
            prompt_token_len = len(self.tokenizer.encode(prompt_text))

        # Fallback: if "उत्तर:" not found then loss on last 30% 
        else:
            prompt_token_len = int(len(full_ids) * 0.7)


        labels = input_ids.clone()
        labels[:prompt_token_len] = -100

            
        return {
            "input_ids":input_ids,
            "labels" : labels, # >> this will use in training
            "text" : text[:200] + "..."
        }

In [43]:
from decoder_only_gpt import My_GPT_model
# Model + checkpoint
DEVICE = "cuda"

model = My_GPT_model(
    vocab_size=tokenizer.get_piece_size(),
    num_layers=12,
    d_model=512,
    d_ff=2048,
    num_heads=8,
    seq_len=512
).to(DEVICE)

ckpt_path = "checkpoints_HindiGPT-v1_step280000.pt"
print(f"Loading checkpoint: {ckpt_path}")
ckpt = torch.load(ckpt_path, map_location=DEVICE)
clean_state_dict = {k.replace("_orig_mod.", ""): v for k, v in ckpt["model"].items()}

Loading checkpoint: checkpoints_HindiGPT-v1_step280000.pt


In [44]:
dataset = HindiSFT_dataset(jsonl_file, tokenizer, max_len=512)

Loading dataset: alpaca_hindi_sft_clean.jsonl
Loaded 36353 valid examples | Skipped: 0


In [45]:
dataset.data[1]

'### प्रश्न:\nतीन प्राथमिक रंग कौन से हैं?\n\n### उत्तर:\nतीन प्राथमिक रंग लाल, नीला और पीला हैं। इन रंगों को प्राथमिक कहा जाता है क्योंकि इन्हें अन्य रंगों को मिलाकर नहीं बनाया जा सकता है और अन्य सभी रंगों को विभिन्न अनुपातों में मिलाकर बनाया जा सकता है। प्रकाश के लिए उपयोग की जाने वाली योगात्मक रंग प्रणाली में, प्राथमिक रंग लाल, हरा और नीला (आर. जी. बी.) हैं।'

In [46]:
from torch.utils.data import DataLoader
dataloader = DataLoader(dataset, batch_size=1, shuffle=True, num_workers=0)

In [47]:
dataloader.dataset.data[1]

'### प्रश्न:\nतीन प्राथमिक रंग कौन से हैं?\n\n### उत्तर:\nतीन प्राथमिक रंग लाल, नीला और पीला हैं। इन रंगों को प्राथमिक कहा जाता है क्योंकि इन्हें अन्य रंगों को मिलाकर नहीं बनाया जा सकता है और अन्य सभी रंगों को विभिन्न अनुपातों में मिलाकर बनाया जा सकता है। प्रकाश के लिए उपयोग की जाने वाली योगात्मक रंग प्रणाली में, प्राथमिक रंग लाल, हरा और नीला (आर. जी. बी.) हैं।'

In [48]:
next(iter(dataloader))

{'input_ids': tensor([[28843,     1,  2821, 28911,     1, 28849,   409,  2948,  7349,   363,
           7438,    40, 25400,   884, 28843,     1, 19033,  1070, 17413,  2350,
              1,  3769,   222,   666,    64, 10791,  1697,    82,  9042,  1026,
          28893, 19203,   361,  1680,    15, 28869,   133,   288,    28, 10847,
             11,  6520,    28,  4554,    44,  3112,    40,  2216,   140,    11,
             91,   398,   144, 13041,  1397,    22,   981,   629,    15, 28869,
              1,   832, 28911,     1,  3769,   222,   666,    64, 10791,  1697,
           1026, 28893, 19203,   361,    11,    91,    82,  9042,  6520,    15,
            176,  8556,    26, 13041,    44,   704,    46,  2616,  1573,    15,
          28869]]),
 'labels': tensor([[ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
           -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
           -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -10

In [49]:
# Loss calculation
# for batch_idx, batch in enumerate(next(iter(dataloader))):
#     logits = model(batch["input_ids"].to(DEVICE))
#     logits

batch = next(iter(dataloader))

input_ids = batch["input_ids"].to(DEVICE)
labels = batch["labels"].to(DEVICE)

model.train()
with torch.no_grad():
    outputs = model(input_ids)

logits=outputs
logits

tensor([[[-1.9621e+01,  5.6535e-02, -1.3188e+01,  ...,  7.9394e+00,
           1.1918e+00,  2.8330e+01],
         [-8.4260e+00,  3.6599e+02,  1.1935e+01,  ...,  1.1067e+01,
           7.2194e+00,  2.2724e+01],
         [ 1.5744e+01,  1.7003e+01, -2.9075e+01,  ...,  3.0255e+01,
           3.9547e+01,  1.4148e+01],
         ...,
         [-3.3509e+00, -1.3258e+01, -1.1324e+01,  ...,  1.4510e+01,
           2.0038e+01, -7.6950e+00],
         [ 4.2681e+01,  2.9652e+01,  5.7498e-02,  ...,  2.2164e+01,
          -9.2041e+00, -2.6461e+01],
         [ 6.6871e+01, -4.1109e+01,  1.1544e+01,  ...,  2.7720e+01,
           2.8109e+01,  2.7611e+01]]], device='cuda:0')

In [50]:
logits.size()

torch.Size([1, 41, 32768])

In [51]:
logits.size(-1)

32768

In [52]:
logits.view(-1, logits.size(-1))

tensor([[-1.9621e+01,  5.6535e-02, -1.3188e+01,  ...,  7.9394e+00,
          1.1918e+00,  2.8330e+01],
        [-8.4260e+00,  3.6599e+02,  1.1935e+01,  ...,  1.1067e+01,
          7.2194e+00,  2.2724e+01],
        [ 1.5744e+01,  1.7003e+01, -2.9075e+01,  ...,  3.0255e+01,
          3.9547e+01,  1.4148e+01],
        ...,
        [-3.3509e+00, -1.3258e+01, -1.1324e+01,  ...,  1.4510e+01,
          2.0038e+01, -7.6950e+00],
        [ 4.2681e+01,  2.9652e+01,  5.7498e-02,  ...,  2.2164e+01,
         -9.2041e+00, -2.6461e+01],
        [ 6.6871e+01, -4.1109e+01,  1.1544e+01,  ...,  2.7720e+01,
          2.8109e+01,  2.7611e+01]], device='cuda:0')

In [53]:
input_ids.view(-1)

tensor([28843,     1,  2821, 28911,     1, 28849,   409,  2948,  7349, 10519,
         1293,    15,   158,  2007, 28910,     1,  1323,  1189,  3243,    32,
        18454, 28869,     1,   832, 28911,     1,    74,  8804,  2007,    15,
          133,  1150,   542,   824,  1323,  1189,  3243,    32, 18454,  2977,
          824], device='cuda:0')

In [54]:
import torch.nn.functional as F
loss = F.cross_entropy(
            logits.view(-1, logits.size(-1)),
            input_ids.view(-1),
            ignore_index=-100  # agar data mein padding nahi toh comment kar ke try kar sakta hai
        )

In [55]:
loss

tensor(0., device='cuda:0')

In [56]:
B, T, V = logits.shape

In [57]:
B, T, V

(1, 41, 32768)

In [82]:
# Z = logits.view(-1, V)        # [(B*T), V]
Z = logits[:, :-1, :].contiguous() 
Z

tensor([[[-1.9621e+01,  5.6535e-02, -1.3188e+01,  ...,  7.9394e+00,
           1.1918e+00,  2.8330e+01],
         [-8.4260e+00,  3.6599e+02,  1.1935e+01,  ...,  1.1067e+01,
           7.2194e+00,  2.2724e+01],
         [ 1.5744e+01,  1.7003e+01, -2.9075e+01,  ...,  3.0255e+01,
           3.9547e+01,  1.4148e+01],
         ...,
         [-1.4601e+01,  4.5014e+01,  5.7467e+00,  ...,  3.9295e+01,
          -1.8206e+01, -2.7503e+01],
         [-3.3509e+00, -1.3258e+01, -1.1324e+01,  ...,  1.4510e+01,
           2.0038e+01, -7.6950e+00],
         [ 4.2681e+01,  2.9652e+01,  5.7498e-02,  ...,  2.2164e+01,
          -9.2041e+00, -2.6461e+01]]], device='cuda:0')

In [83]:
# y = labels.view(-1)           # [(B*T)]
y = labels[:, 1:].contiguous()
y

tensor([[ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,     1,    74,  8804,  2007,    15,   133,
          1150,   542,   824,  1323,  1189,  3243,    32, 18454,  2977,   824]],
       device='cuda:0')

In [85]:
Z = Z.view(-1, V)
Z

tensor([[-1.9621e+01,  5.6535e-02, -1.3188e+01,  ...,  7.9394e+00,
          1.1918e+00,  2.8330e+01],
        [-8.4260e+00,  3.6599e+02,  1.1935e+01,  ...,  1.1067e+01,
          7.2194e+00,  2.2724e+01],
        [ 1.5744e+01,  1.7003e+01, -2.9075e+01,  ...,  3.0255e+01,
          3.9547e+01,  1.4148e+01],
        ...,
        [-1.4601e+01,  4.5014e+01,  5.7467e+00,  ...,  3.9295e+01,
         -1.8206e+01, -2.7503e+01],
        [-3.3509e+00, -1.3258e+01, -1.1324e+01,  ...,  1.4510e+01,
          2.0038e+01, -7.6950e+00],
        [ 4.2681e+01,  2.9652e+01,  5.7498e-02,  ...,  2.2164e+01,
         -9.2041e+00, -2.6461e+01]], device='cuda:0')

In [86]:
y = y.view(-1)
y

tensor([ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,  -100,  -100,     1,    74,  8804,  2007,    15,   133,
         1150,   542,   824,  1323,  1189,  3243,    32, 18454,  2977,   824],
       device='cuda:0')

In [87]:
mask = (y != -100)            # [(B*T)]
mask

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       device='cuda:0')

In [88]:
log_probs = Z - torch.logsumexp(Z, dim=1, keepdim=True)

In [89]:
log_probs

tensor([[-358.0633, -338.3859, -351.6307,  ..., -330.5030, -337.2506,
         -310.1125],
        [-374.4157,    0.0000, -354.0551,  ..., -354.9228, -358.7702,
         -343.2652],
        [-374.1662, -372.9077, -418.9851,  ..., -359.6560, -350.3635,
         -375.7625],
        ...,
        [-449.6099, -389.9943, -429.2620,  ..., -395.7139, -453.2150,
         -462.5119],
        [-438.1372, -448.0448, -446.1102,  ..., -420.2765, -414.7481,
         -442.4814],
        [-365.4791, -378.5081, -408.1024,  ..., -385.9955, -417.3640,
         -434.6210]], device='cuda:0')

In [90]:
valid_log_probs = log_probs[mask]
valid_log_probs

tensor([[-408.5417, -417.5915, -463.0161,  ..., -415.4218, -419.4056,
         -417.9012],
        [-443.0731,    0.0000, -435.2951,  ..., -440.7094, -435.6548,
         -434.6825],
        [-442.4801, -433.6578, -451.7408,  ..., -420.7683, -390.5049,
         -404.7467],
        ...,
        [-449.6099, -389.9943, -429.2620,  ..., -395.7139, -453.2150,
         -462.5119],
        [-438.1372, -448.0448, -446.1102,  ..., -420.2765, -414.7481,
         -442.4814],
        [-365.4791, -378.5081, -408.1024,  ..., -385.9955, -417.3640,
         -434.6210]], device='cuda:0')

In [91]:
valid_labels = y[mask]
valid_labels

tensor([    1,    74,  8804,  2007,    15,   133,  1150,   542,   824,  1323,
         1189,  3243,    32, 18454,  2977,   824], device='cuda:0')

In [92]:
token_logp = valid_log_probs.gather(1, valid_labels.unsqueeze(1)).squeeze()
token_logp

tensor([-417.5915, -438.8288, -462.1162, -444.0145, -446.6161, -440.2321,
        -433.3185, -445.9480, -441.9668, -400.3585, -492.6258, -466.7554,
        -434.6844, -436.6280, -465.1490, -414.3974], device='cuda:0')

In [93]:
loss = -token_logp.mean()
loss

tensor(442.5769, device='cuda:0')

In [61]:
Z.max()

tensor(485.6451, device='cuda:0')

In [62]:
Z.max(dim=1)

torch.return_types.max(
values=tensor([338.4424, 365.9897, 389.9105, 379.5609, 388.2888, 373.9313, 404.8646,
        403.2023, 411.2794, 426.4887, 420.0305, 408.7266, 413.1277, 438.3163,
        428.7708, 427.7282, 478.4535, 463.7632, 433.8236, 430.4994, 427.6882,
        432.4855, 434.7180, 424.7376, 430.3039, 439.2667, 443.8549, 469.9390,
        447.1976, 426.4161, 436.7174, 429.0020, 434.8603, 438.3012, 485.6451,
        473.2752, 440.7137, 435.0087, 434.7863, 408.1599, 436.5043],
       device='cuda:0'),
indices=tensor([28843,     1,  2821, 28911,     1, 28849,   409,  2948,  7349, 10519,
         1293,    15,   158,  2007, 28910,     1,  1323,  1189,  3243,    32,
        18454, 28869,     1,   832, 28911,     1,    74,  8804,  2007,    15,
          133,  1150,   542,   824,  1323,  1189,  3243,    32, 18454,  2977,
          824], device='cuda:0'))

In [63]:
Z.max(dim=1, keepdim=True)

torch.return_types.max(
values=tensor([[338.4424],
        [365.9897],
        [389.9105],
        [379.5609],
        [388.2888],
        [373.9313],
        [404.8646],
        [403.2023],
        [411.2794],
        [426.4887],
        [420.0305],
        [408.7266],
        [413.1277],
        [438.3163],
        [428.7708],
        [427.7282],
        [478.4535],
        [463.7632],
        [433.8236],
        [430.4994],
        [427.6882],
        [432.4855],
        [434.7180],
        [424.7376],
        [430.3039],
        [439.2667],
        [443.8549],
        [469.9390],
        [447.1976],
        [426.4161],
        [436.7174],
        [429.0020],
        [434.8603],
        [438.3012],
        [485.6451],
        [473.2752],
        [440.7137],
        [435.0087],
        [434.7863],
        [408.1599],
        [436.5043]], device='cuda:0'),
indices=tensor([[28843],
        [    1],
        [ 2821],
        [28911],
        [    1],
        [28849],
        [  409],
   

In [64]:
Z.max(dim=1, keepdim=True).values

tensor([[338.4424],
        [365.9897],
        [389.9105],
        [379.5609],
        [388.2888],
        [373.9313],
        [404.8646],
        [403.2023],
        [411.2794],
        [426.4887],
        [420.0305],
        [408.7266],
        [413.1277],
        [438.3163],
        [428.7708],
        [427.7282],
        [478.4535],
        [463.7632],
        [433.8236],
        [430.4994],
        [427.6882],
        [432.4855],
        [434.7180],
        [424.7376],
        [430.3039],
        [439.2667],
        [443.8549],
        [469.9390],
        [447.1976],
        [426.4161],
        [436.7174],
        [429.0020],
        [434.8603],
        [438.3012],
        [485.6451],
        [473.2752],
        [440.7137],
        [435.0087],
        [434.7863],
        [408.1599],
        [436.5043]], device='cuda:0')

In [65]:
Z_max = Z.max(dim=1, keepdim=True).values

In [66]:
Z_stable = Z - Z_max
Z_stable

tensor([[-358.0633, -338.3859, -351.6307,  ..., -330.5030, -337.2506,
         -310.1125],
        [-374.4157,    0.0000, -354.0551,  ..., -354.9228, -358.7702,
         -343.2652],
        [-374.1662, -372.9077, -418.9851,  ..., -359.6560, -350.3635,
         -375.7625],
        ...,
        [-438.1372, -448.0448, -446.1102,  ..., -420.2765, -414.7481,
         -442.4814],
        [-365.4791, -378.5081, -408.1024,  ..., -385.9955, -417.3640,
         -434.6210],
        [-369.6336, -477.6129, -424.9607,  ..., -408.7841, -408.3954,
         -408.8929]], device='cuda:0')

In [67]:
exp_Z = torch.exp(Z_stable)               # [(B*T), V]
exp_Z

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')

In [68]:
sum_exp_Z = exp_Z.sum(dim=1, keepdim=True)  # [(B*T), 1]
sum_exp_Z

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], device='cuda:0')

In [69]:
probs = exp_Z / sum_exp_Z                  # [(B*T), V]
probs

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')

In [72]:
probs.shape

torch.Size([41, 32768])

In [74]:
# gather p_{i, y_i}
# true_probs = probs.gather(1, y.unsqueeze(1)).squeeze(1)
# true_probs

N, C = probs.shape

true_probs = []
for i in range(N):
    true_probs.append(probs[i, y[i]])

true_probs = torch.tensor(true_probs)

In [75]:
true_probs

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [76]:
token_loss = -torch.log(true_probs)       # [(B*T)]
token_loss

tensor([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.])

In [79]:
mask = (y != -100)
loss = (token_loss.to(DEVICE) * mask).sum() / mask.sum()

In [80]:
loss

tensor(0., device='cuda:0')

In [81]:
loss.item()

0.0

In [94]:
F.cross_entropy(
    logits[:, :-1, :].reshape(-1, V),
    labels[:, 1:].reshape(-1),
    ignore_index=-100
)

tensor(442.5769, device='cuda:0')

In [2]:
@torch.no_grad()
def generate(
    model,
    input_ids,
    max_new_tokens=50,
    temperature=1.0,
    top_p=0.9
):
    model.eval()

    for _ in range(max_new_tokens):
        # forward
        logits = model(input_ids)              # (B, S, V)
        logits = logits[:, -1, :] / temperature

        # ---- nucleus (top-p) sampling ----
        probs = torch.softmax(logits, dim=-1)
        sorted_probs, sorted_idx = torch.sort(probs, descending=True)

        cum_probs = torch.cumsum(sorted_probs, dim=-1)
        mask = cum_probs > top_p
        mask[:, 1:] = mask[:, :-1].clone()
        mask[:, 0] = False

        sorted_probs[mask] = 0.0
        sorted_probs /= sorted_probs.sum(dim=-1, keepdim=True)

        next_token = torch.multinomial(sorted_probs, 1)
        next_token = torch.gather(sorted_idx, -1, next_token)

        # append
        input_ids = torch.cat([input_ids, next_token], dim=1)

    return input_ids


In [3]:
# full_sft_final_attempt_with_tqdm_perplexity.py
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
import json
import sentencepiece as spm
from decoder_only_gpt import My_GPT_model
from tqdm import tqdm  # ← Yeh add kar diya
import math  # perplexity ke liye

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

# Tokenizer
sp = spm.SentencePieceProcessor()
sp.load("hindi_tokenizer_new.model")
print("Tokenizer loaded. Vocab size:", sp.get_piece_size())

# Model + checkpoint
model = My_GPT_model(
    vocab_size=sp.get_piece_size(),
    num_layers=12,
    d_model=512,
    d_ff=2048,
    num_heads=8,
    seq_len=512
).to(DEVICE)

ckpt_path = "checkpoints_HindiGPT-v1_step280000.pt"
print(f"Loading checkpoint: {ckpt_path}")
ckpt = torch.load(ckpt_path, map_location=DEVICE)
clean_state_dict = {k.replace("_orig_mod.", ""): v for k, v in ckpt["model"].items()}
missing, unexpected = model.load_state_dict(clean_state_dict, strict=False)
print("Missing keys:", len(missing), "Unexpected keys:", len(unexpected))

# Dataset class (tera improved wala)
class HindiSFTDataset(Dataset):
    def __init__(self, jsonl_file, tokenizer, max_len=512):
        self.tokenizer = tokenizer
        self.max_len = max_len
        self.data = []

        with open(jsonl_file, "r", encoding="utf-8") as f:
            for line_no, line in enumerate(f):
                line = line.strip()
                if not line:
                    continue

                try:
                    obj = json.loads(line)
                    text = obj["text"].strip()   # 🔥 DIRECT access

                    # sanity filter
                    if "### उत्तर:" not in text:
                        continue

                    self.data.append(text)

                except Exception as e:
                    print(f"[ERROR line {line_no}] {e}")

        print(f"Loaded SFT samples: {len(self.data)}")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        text = self.data[idx]

        # tokenize
        full_ids = self.tokenizer.encode(text)
        if len(full_ids) > self.max_len:
            full_ids = full_ids[:self.max_len]

        input_ids = torch.tensor(full_ids, dtype=torch.long)

        # === ANSWER-ONLY LOSS ===
        ans_pos = text.find("### उत्तर:")
        prompt_text = text[:ans_pos + len("### उत्तर:")]
        prompt_len = len(self.tokenizer.encode(prompt_text))

        labels = input_ids.clone()
        labels[:prompt_len] = -100

        return {
            "input_ids": input_ids,
            "labels": labels
        }




def collate_fn(batch):
    max_len = max(len(x["input_ids"]) for x in batch)

    input_ids, labels, attn_masks = [], [], []

    for item in batch:
        ids = item["input_ids"]
        lbl = item["labels"]

        pad_len = max_len - len(ids)

        input_ids.append(
            torch.cat([ids, torch.zeros(pad_len, dtype=torch.long)])
        )
        labels.append(
            torch.cat([lbl, torch.full((pad_len,), -100)])
        )

        attn_masks.append(
            torch.cat([torch.ones(len(ids)), torch.zeros(pad_len)])
        )

    return {
        "input_ids": torch.stack(input_ids),
        "labels": torch.stack(labels),
        "attention_mask": torch.stack(attn_masks)
    }





# Load dataset
jsonl_file = "alpaca_hindi_sft_clean.jsonl"
dataset = HindiSFTDataset(jsonl_file, sp)

print("DATASET SIZE =", len(dataset))
print("FIRST 2 RAW SAMPLES =", dataset.data[:2])

dataloader = DataLoader(dataset, batch_size=2, shuffle=True, collate_fn=collate_fn)

# Optimizer + Scheduler
optimizer = AdamW(model.parameters(), lr=8e-5, betas=(0.9, 0.98), eps=1e-6)
scheduler = CosineAnnealingLR(optimizer, T_max=len(dataloader) * 5, eta_min=1e-7)

model.train()
print("Training started!")

for epoch in range(5):
    total_loss = 0.0
    num_batches = 0
    global_step = 0

    # tqdm progress bar add kar diya (epoch ke andar)
    progress_bar = tqdm(dataloader, desc=f"Epoch {epoch+1}", leave=True)

    for batch_idx, batch in enumerate(progress_bar):
        input_ids = batch["input_ids"].to(DEVICE)
        labels = batch["labels"].to(DEVICE)
        # attention_mask = batch["attention_mask"].to(DEVICE)
        
        logits = model(input_ids)
        
        loss = F.cross_entropy(
            logits[:, :-1, :].contiguous().view(-1, logits.size(-1)),
            labels[:, 1:].contiguous().view(-1),
            ignore_index=-100
        )

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=3.0)
        optimizer.step()
        scheduler.step()

        
        # ---- SANITY CHECK GENERATION ----
        if global_step % 2000 == 0:
            model.eval()
            with torch.no_grad():
                prompt = "प्रश्न: स्वस्थ रहने के उपाय बताइए।\n\nउत्तर:"
                prompt_ids = torch.tensor([sp.encode(prompt)], device=DEVICE)
                
                generated_ids = generate(
                    model,
                    prompt_ids,
                    max_new_tokens=80,
                    temperature=0.8,
                    top_p=0.9
                )
                
                # print(sp.decode(generated_ids[0].tolist()))
        
                print("\n" + "=" * 60)
                print("GENERATION @ step", global_step)
                print(sp.decode(generated_ids[0].tolist()))
                print("=" * 60 + "\n")
                
                global_step += 1
            model.train()
# --------------------------------

        total_loss += loss.item()
        num_batches += 1

        # tqdm mein live loss aur LR update karte hain
        current_lr = scheduler.get_last_lr()[0]
        progress_bar.set_postfix({
            'loss': f'{loss.item():.4f}',
            'lr': f'{current_lr:.2e}'
        })
        
        if batch_idx % 500 == 0:
            print(f"Step {batch_idx} | Loss {loss.item():.3f}")

        if batch_idx % 10000 == 0 and batch_idx > 0:
            save_path = f"full_sft_epoch{epoch+1}_step{batch_idx}.pt"
            torch.save(model.state_dict(), save_path)
            print(f"Saved checkpoint: {save_path}")

    avg_loss = total_loss / num_batches if num_batches > 0 else 0

    # Perplexity calculate kar (bahut meaningful metric LM ke liye)
    perplexity = math.exp(avg_loss)
    print(f"Epoch {epoch+1} completed | Avg Loss: {avg_loss:.4f} | Perplexity: {perplexity:.2f}")

# Final save
final_path = "full_sft_final.pt"
torch.save(model.state_dict(), final_path)
print(f"Full SFT complete! Final model saved as: {final_path}")

Using device: cuda
Tokenizer loaded. Vocab size: 32768
Loading checkpoint: checkpoints_HindiGPT-v1_step280000.pt
Missing keys: 0 Unexpected keys: 0
Loaded SFT samples: 36353
DATASET SIZE = 36353
FIRST 2 RAW SAMPLES = ['### प्रश्न:\nस्वस्थ रहने के लिए तीन सुझाव दें।\n\n### उत्तर:\n1. संतुलित और पौष्टिक आहार लेंः सुनिश्चित करें कि आपके भोजन में विभिन्न प्रकार के फल और सब्जियां, दुबला प्रोटीन, साबुत अनाज और स्वस्थ वसा शामिल हों। यह आपके शरीर को सर्वोत्तम रूप से कार्य करने के लिए आवश्यक पोषक तत्व प्रदान करने में मदद करता है और पुरानी बीमारियों को रोकने में मदद कर सकता है।\n\n2. नियमित शारीरिक गतिविधि में संलग्न रहेंः मजबूत हड्डियों, मांसपेशियों और हृदय स्वास्थ्य को बनाए रखने के लिए व्यायाम महत्वपूर्ण है। प्रत्येक सप्ताह कम से कम 150 मिनट के मध्यम एरोबिक व्यायाम या 75 मिनट के जोरदार व्यायाम का लक्ष्य रखें।\n\n3. पर्याप्त नींद लेंः पर्याप्त गुणवत्ता वाली नींद लेना शारीरिक और मानसिक कल्याण के लिए महत्वपूर्ण है। यह मनोदशा को नियंत्रित करने, संज्ञानात्मक कार्य में सुधार करने और स्वस्थ विकास और 

Epoch 1:   0%|                                           | 2/18177 [00:01<3:51:05,  1.31it/s, loss=4.7898, lr=8.00e-05]


GENERATION @ step 0
प्रश्न: स्वस्थ रहने के उपाय बताइए। ⁇ उत्तर: आयुर्वेद में आयुर्वेद के अंतर्गत अनेक लाभ हैं, जैसे कि, आयुर्वेद में अनेक लाभ व स्वास्थ्य लाभ के अन्य लाभ, साथ ही आयुर्वेद में अनेक लाभ, हिन्दू धर्म में अनेक लाभ व स्वास्थ्य लाभ के अन्य लाभ। आयुर्वेद में अनेक लाभ व स्वास्थ्य लाभ के अन्य लाभ, आयुर्वेद में अनेक लाभ व स्वास्थ्य लाभ के अन्य लाभ। आयुर्वेद में अनेक लाभ व स्वास्थ्य लाभ के अन्य लाभ। आयुर्वेद में अनेक लाभ

Step 0 | Loss 3.609


Epoch 1:   3%|█▏                                         | 502/18177 [01:53<57:05,  5.16it/s, loss=3.2495, lr=8.00e-05]

Step 500 | Loss 2.856


Epoch 1:   6%|██▎                                       | 1001/18177 [03:46<48:39,  5.88it/s, loss=3.3874, lr=8.00e-05]

Step 1000 | Loss 3.387


Epoch 1:   8%|███▍                                      | 1502/18177 [05:46<44:52,  6.19it/s, loss=2.7619, lr=7.99e-05]

Step 1500 | Loss 2.948


Epoch 1:  11%|████▍                                   | 2002/18177 [07:38<1:32:04,  2.93it/s, loss=3.4052, lr=7.99e-05]

Step 2000 | Loss 2.799


Epoch 1:  14%|█████▊                                    | 2501/18177 [09:35<43:01,  6.07it/s, loss=2.9028, lr=7.99e-05]

Step 2500 | Loss 2.903


Epoch 1:  17%|██████▌                                 | 3002/18177 [11:27<1:15:36,  3.34it/s, loss=3.3023, lr=7.98e-05]

Step 3000 | Loss 3.606


Epoch 1:  19%|███████▋                                | 3501/18177 [13:15<1:14:14,  3.29it/s, loss=3.5011, lr=7.97e-05]

Step 3500 | Loss 3.501


Epoch 1:  22%|█████████▏                                | 4002/18177 [15:13<57:06,  4.14it/s, loss=4.4217, lr=7.96e-05]

Step 4000 | Loss 3.327


Epoch 1:  25%|██████████▍                               | 4502/18177 [17:05<39:09,  5.82it/s, loss=3.5696, lr=7.95e-05]

Step 4500 | Loss 3.175


Epoch 1:  28%|███████████▌                              | 5002/18177 [18:57<46:27,  4.73it/s, loss=3.6876, lr=7.94e-05]

Step 5000 | Loss 2.447


Epoch 1:  30%|████████████▋                             | 5502/18177 [20:54<48:45,  4.33it/s, loss=2.6376, lr=7.93e-05]

Step 5500 | Loss 3.733


Epoch 1:  33%|█████████████▊                            | 6002/18177 [22:42<50:21,  4.03it/s, loss=2.9303, lr=7.91e-05]

Step 6000 | Loss 3.579


Epoch 1:  36%|███████████████                           | 6502/18177 [24:25<26:54,  7.23it/s, loss=3.6872, lr=7.90e-05]

Step 6500 | Loss 3.688


Epoch 1:  39%|████████████████▏                         | 7001/18177 [26:17<26:07,  7.13it/s, loss=2.4083, lr=7.88e-05]

Step 7000 | Loss 2.408


Epoch 1:  41%|█████████████████▎                        | 7501/18177 [28:04<30:28,  5.84it/s, loss=3.2662, lr=7.87e-05]

Step 7500 | Loss 3.266


Epoch 1:  44%|██████████████████▍                       | 8001/18177 [29:55<28:12,  6.01it/s, loss=4.9393, lr=7.85e-05]

Step 8000 | Loss 4.939


Epoch 1:  47%|███████████████████▋                      | 8502/18177 [31:45<31:50,  5.07it/s, loss=3.6880, lr=7.83e-05]

Step 8500 | Loss 3.102


Epoch 1:  50%|████████████████████▊                     | 9001/18177 [33:38<25:01,  6.11it/s, loss=2.9444, lr=7.81e-05]

Step 9000 | Loss 2.944


Epoch 1:  52%|█████████████████████▉                    | 9502/18177 [35:29<49:58,  2.89it/s, loss=3.0109, lr=7.79e-05]

Step 9500 | Loss 2.938


Epoch 1:  55%|██████████████████████▌                  | 10000/18177 [37:25<44:45,  3.04it/s, loss=2.8292, lr=7.76e-05]

Step 10000 | Loss 2.829


Epoch 1:  55%|██████████████████████▌                  | 10001/18177 [37:26<53:41,  2.54it/s, loss=2.8292, lr=7.76e-05]

Saved checkpoint: full_sft_epoch1_step10000.pt


Epoch 1:  58%|███████████████████████▋                 | 10501/18177 [39:22<18:41,  6.84it/s, loss=3.1330, lr=7.74e-05]

Step 10500 | Loss 3.133


Epoch 1:  61%|████████████████████████▊                | 11002/18177 [41:14<27:10,  4.40it/s, loss=2.8790, lr=7.71e-05]

Step 11000 | Loss 3.302


Epoch 1:  63%|█████████████████████████▉               | 11502/18177 [43:09<19:55,  5.58it/s, loss=2.9455, lr=7.69e-05]

Step 11500 | Loss 3.034


Epoch 1:  66%|███████████████████████████              | 12002/18177 [45:01<18:39,  5.51it/s, loss=2.6374, lr=7.66e-05]

Step 12000 | Loss 2.672


Epoch 1:  69%|████████████████████████████▏            | 12502/18177 [46:48<13:54,  6.80it/s, loss=3.3544, lr=7.63e-05]

Step 12500 | Loss 3.314


Epoch 1:  72%|█████████████████████████████▎           | 13002/18177 [48:38<14:08,  6.10it/s, loss=2.4750, lr=7.60e-05]

Step 13000 | Loss 3.191


Epoch 1:  74%|██████████████████████████████▍          | 13501/18177 [50:24<18:11,  4.29it/s, loss=2.8222, lr=7.57e-05]

Step 13500 | Loss 2.822


Epoch 1:  77%|███████████████████████████████▌         | 14002/18177 [52:19<13:31,  5.15it/s, loss=2.7663, lr=7.54e-05]

Step 14000 | Loss 2.633


Epoch 1:  80%|████████████████████████████████▋        | 14501/18177 [54:15<11:57,  5.13it/s, loss=3.9915, lr=7.51e-05]

Step 14500 | Loss 3.356


Epoch 1:  83%|█████████████████████████████████▊       | 15002/18177 [56:02<11:56,  4.43it/s, loss=2.2574, lr=7.47e-05]

Step 15000 | Loss 3.461


Epoch 1:  85%|██████████████████████████████████▉      | 15501/18177 [57:59<12:26,  3.58it/s, loss=3.0122, lr=7.44e-05]

Step 15500 | Loss 3.012


Epoch 1:  88%|████████████████████████████████████     | 16001/18177 [59:45<07:25,  4.88it/s, loss=4.2344, lr=7.40e-05]

Step 16000 | Loss 4.234


Epoch 1:  91%|███████████████████████████████████▍   | 16501/18177 [1:01:30<04:40,  5.97it/s, loss=2.6780, lr=7.37e-05]

Step 16500 | Loss 2.678


Epoch 1:  94%|████████████████████████████████████▍  | 17002/18177 [1:03:17<03:27,  5.67it/s, loss=2.0136, lr=7.33e-05]

Step 17000 | Loss 2.976


Epoch 1:  96%|█████████████████████████████████████▌ | 17502/18177 [1:05:07<01:47,  6.29it/s, loss=4.1008, lr=7.29e-05]

Step 17500 | Loss 3.362


Epoch 1:  99%|██████████████████████████████████████▌| 18001/18177 [1:06:58<00:27,  6.35it/s, loss=2.3623, lr=7.25e-05]

Step 18000 | Loss 2.362


Epoch 1: 100%|███████████████████████████████████████| 18177/18177 [1:07:39<00:00,  4.48it/s, loss=1.5147, lr=7.24e-05]


Epoch 1 completed | Avg Loss: 3.1603 | Perplexity: 23.58


Epoch 2:   0%|                                           | 1/18177 [00:01<8:40:35,  1.72s/it, loss=2.5121, lr=7.24e-05]


GENERATION @ step 0
प्रश्न: स्वस्थ रहने के उपाय बताइए। ⁇ उत्तर: यहाँ एक स्पष्ट- संगीत है, जिसमें "स्मार्ट" के साथ "सपनों" के साथ "टेट" के साथ एक स्पष्ट और स्पष्ट भावना है। " ⁇ प्रौद्योगिकी की प्रगति ने छात्रों के लिए अधिक कुशल और कुशल तरीके से सीखने और विकसित होने के लिए एक प्रभावी समाधान प्रदान किया है। इसका उपयोग छात्रों को अधिक कुशल और कुशल तरीके से सीखने में सक्षम बनाता है,

Step 0 | Loss 2.512


Epoch 2:   3%|█▏                                         | 502/18177 [01:52<55:08,  5.34it/s, loss=3.0652, lr=7.20e-05]

Step 500 | Loss 3.126


Epoch 2:   6%|██▏                                     | 1001/18177 [03:39<2:16:32,  2.10it/s, loss=2.5567, lr=7.15e-05]

Step 1000 | Loss 2.557


Epoch 2:   8%|███▍                                      | 1502/18177 [05:35<42:17,  6.57it/s, loss=3.4412, lr=7.11e-05]

Step 1500 | Loss 2.932


Epoch 2:  11%|████▋                                     | 2002/18177 [07:25<58:05,  4.64it/s, loss=2.2945, lr=7.07e-05]

Step 2000 | Loss 3.349


Epoch 2:  14%|█████▊                                    | 2502/18177 [09:13<49:11,  5.31it/s, loss=1.9449, lr=7.02e-05]

Step 2500 | Loss 2.806


Epoch 2:  17%|██████▉                                   | 3002/18177 [11:05<52:41,  4.80it/s, loss=3.2562, lr=6.98e-05]

Step 3000 | Loss 2.902


Epoch 2:  19%|████████                                  | 3502/18177 [12:59<42:51,  5.71it/s, loss=4.0421, lr=6.93e-05]

Step 3500 | Loss 2.594


Epoch 2:  22%|█████████▏                                | 4002/18177 [14:53<34:22,  6.87it/s, loss=3.1064, lr=6.88e-05]

Step 4000 | Loss 2.189


Epoch 2:  25%|██████████▍                               | 4502/18177 [16:48<45:23,  5.02it/s, loss=2.3650, lr=6.83e-05]

Step 4500 | Loss 3.020


Epoch 2:  28%|███████████▌                              | 5002/18177 [18:42<45:52,  4.79it/s, loss=2.7567, lr=6.78e-05]

Step 5000 | Loss 3.376


Epoch 2:  30%|████████████▋                             | 5502/18177 [20:33<37:14,  5.67it/s, loss=2.8911, lr=6.73e-05]

Step 5500 | Loss 2.923


Epoch 2:  33%|█████████████▊                            | 6001/18177 [22:18<48:24,  4.19it/s, loss=2.9576, lr=6.68e-05]

Step 6000 | Loss 2.895


Epoch 2:  36%|███████████████                           | 6502/18177 [24:07<35:25,  5.49it/s, loss=3.3570, lr=6.63e-05]

Step 6500 | Loss 2.374


Epoch 2:  39%|████████████████▏                         | 7002/18177 [25:56<25:24,  7.33it/s, loss=1.6822, lr=6.58e-05]

Step 7000 | Loss 3.402


Epoch 2:  41%|█████████████████▎                        | 7502/18177 [27:49<29:41,  5.99it/s, loss=2.2909, lr=6.53e-05]

Step 7500 | Loss 3.301


Epoch 2:  44%|██████████████████▍                       | 8001/18177 [29:39<42:40,  3.97it/s, loss=3.9455, lr=6.47e-05]

Step 8000 | Loss 3.946


Epoch 2:  47%|██████████████████▋                     | 8501/18177 [31:35<1:14:00,  2.18it/s, loss=3.2180, lr=6.42e-05]

Step 8500 | Loss 3.218


Epoch 2:  50%|████████████████████▊                     | 9002/18177 [33:25<39:32,  3.87it/s, loss=3.3284, lr=6.36e-05]

Step 9000 | Loss 3.198


Epoch 2:  52%|█████████████████████▉                    | 9502/18177 [35:17<24:17,  5.95it/s, loss=2.4304, lr=6.31e-05]

Step 9500 | Loss 3.399


Epoch 2:  55%|██████████████████████▌                  | 10000/18177 [37:12<23:34,  5.78it/s, loss=2.6903, lr=6.25e-05]

Step 10000 | Loss 2.690


Epoch 2:  55%|██████████████████████▌                  | 10002/18177 [37:13<32:00,  4.26it/s, loss=2.5927, lr=6.25e-05]

Saved checkpoint: full_sft_epoch2_step10000.pt


Epoch 2:  58%|███████████████████████▋                 | 10501/18177 [38:59<18:44,  6.83it/s, loss=3.1320, lr=6.19e-05]

Step 10500 | Loss 3.132


Epoch 2:  61%|████████████████████████▊                | 11002/18177 [40:49<21:25,  5.58it/s, loss=3.0844, lr=6.13e-05]

Step 11000 | Loss 3.391


Epoch 2:  63%|█████████████████████████▉               | 11502/18177 [42:36<25:29,  4.36it/s, loss=1.9407, lr=6.08e-05]

Step 11500 | Loss 3.217


Epoch 2:  66%|███████████████████████████              | 12002/18177 [44:30<15:36,  6.60it/s, loss=2.1603, lr=6.02e-05]

Step 12000 | Loss 3.197


Epoch 2:  69%|████████████████████████████▏            | 12502/18177 [46:30<24:47,  3.82it/s, loss=3.5614, lr=5.96e-05]

Step 12500 | Loss 3.907


Epoch 2:  72%|█████████████████████████████▎           | 13002/18177 [48:19<18:47,  4.59it/s, loss=3.4374, lr=5.90e-05]

Step 13000 | Loss 3.945


Epoch 2:  74%|██████████████████████████████▍          | 13502/18177 [50:16<12:43,  6.12it/s, loss=2.5615, lr=5.83e-05]

Step 13500 | Loss 3.863


Epoch 2:  77%|███████████████████████████████▌         | 14002/18177 [52:11<13:18,  5.23it/s, loss=2.4069, lr=5.77e-05]

Step 14000 | Loss 3.414


Epoch 2:  80%|████████████████████████████████▋        | 14502/18177 [53:58<10:30,  5.83it/s, loss=2.9203, lr=5.71e-05]

Step 14500 | Loss 3.300


Epoch 2:  83%|█████████████████████████████████▊       | 15002/18177 [55:52<13:58,  3.79it/s, loss=2.3409, lr=5.65e-05]

Step 15000 | Loss 3.140


Epoch 2:  85%|██████████████████████████████████▉      | 15501/18177 [57:49<07:51,  5.67it/s, loss=2.5018, lr=5.59e-05]

Step 15500 | Loss 3.082


Epoch 2:  88%|████████████████████████████████████     | 16001/18177 [59:34<07:28,  4.85it/s, loss=3.2926, lr=5.52e-05]

Step 16000 | Loss 3.293


Epoch 2:  91%|███████████████████████████████████▍   | 16502/18177 [1:01:19<03:57,  7.05it/s, loss=2.8166, lr=5.46e-05]

Step 16500 | Loss 2.745


Epoch 2:  94%|████████████████████████████████████▍  | 17002/18177 [1:03:12<02:32,  7.69it/s, loss=2.0512, lr=5.39e-05]

Step 17000 | Loss 1.960


Epoch 2:  96%|█████████████████████████████████████▌ | 17501/18177 [1:05:06<03:37,  3.11it/s, loss=2.8181, lr=5.33e-05]

Step 17500 | Loss 2.818


Epoch 2:  99%|██████████████████████████████████████▌| 18002/18177 [1:06:57<00:26,  6.62it/s, loss=2.6502, lr=5.26e-05]

Step 18000 | Loss 2.780


Epoch 2: 100%|███████████████████████████████████████| 18177/18177 [1:07:36<00:00,  4.48it/s, loss=1.4643, lr=5.24e-05]


Epoch 2 completed | Avg Loss: 2.9129 | Perplexity: 18.41


Epoch 3:   0%|                                           | 1/18177 [00:01<8:14:13,  1.63s/it, loss=3.2914, lr=5.24e-05]


GENERATION @ step 0
प्रश्न: स्वस्थ रहने के उपाय बताइए। ⁇ उत्तर: डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी। डी, डी। डी। डी। डी। डी। डी। डी, डी, डी, डी, डी, डी, डी, डी और

Step 0 | Loss 2.052


Epoch 3:   3%|█▏                                         | 502/18177 [01:52<44:56,  6.56it/s, loss=2.3748, lr=5.17e-05]

Step 500 | Loss 2.153


Epoch 3:   6%|██▎                                       | 1002/18177 [03:47<49:02,  5.84it/s, loss=3.1635, lr=5.11e-05]

Step 1000 | Loss 2.045


Epoch 3:   8%|███▎                                    | 1502/18177 [05:40<1:00:09,  4.62it/s, loss=2.5539, lr=5.04e-05]

Step 1500 | Loss 2.933


Epoch 3:  11%|████▋                                     | 2002/18177 [07:29<58:03,  4.64it/s, loss=3.5578, lr=4.97e-05]

Step 2000 | Loss 2.430


Epoch 3:  14%|█████▊                                    | 2502/18177 [09:15<41:21,  6.32it/s, loss=2.2003, lr=4.91e-05]

Step 2500 | Loss 3.060


Epoch 3:  17%|██████▉                                   | 3002/18177 [11:09<39:25,  6.42it/s, loss=3.8053, lr=4.84e-05]

Step 3000 | Loss 2.271


Epoch 3:  19%|████████                                  | 3502/18177 [12:58<48:59,  4.99it/s, loss=3.1053, lr=4.77e-05]

Step 3500 | Loss 2.671


Epoch 3:  22%|█████████▏                                | 4001/18177 [14:48<47:12,  5.00it/s, loss=1.7927, lr=4.70e-05]

Step 4000 | Loss 1.793


Epoch 3:  25%|██████████▍                               | 4502/18177 [16:38<47:30,  4.80it/s, loss=2.0534, lr=4.64e-05]

Step 4500 | Loss 2.700


Epoch 3:  28%|███████████                             | 5001/18177 [18:34<1:17:32,  2.83it/s, loss=2.8534, lr=4.57e-05]

Step 5000 | Loss 2.853


Epoch 3:  30%|████████████▋                             | 5502/18177 [20:34<36:02,  5.86it/s, loss=2.4138, lr=4.50e-05]

Step 5500 | Loss 3.060


Epoch 3:  33%|█████████████▊                            | 6002/18177 [22:26<29:15,  6.93it/s, loss=3.0747, lr=4.43e-05]

Step 6000 | Loss 3.040


Epoch 3:  36%|███████████████                           | 6502/18177 [24:22<56:23,  3.45it/s, loss=3.2045, lr=4.36e-05]

Step 6500 | Loss 2.543


Epoch 3:  39%|████████████████▏                         | 7003/18177 [26:14<27:25,  6.79it/s, loss=0.7119, lr=4.29e-05]

Step 7000 | Loss 2.872


Epoch 3:  41%|█████████████████▎                        | 7502/18177 [28:09<29:51,  5.96it/s, loss=3.3469, lr=4.22e-05]

Step 7500 | Loss 2.487


Epoch 3:  44%|██████████████████▍                       | 8002/18177 [30:03<44:36,  3.80it/s, loss=2.6807, lr=4.16e-05]

Step 8000 | Loss 2.773


Epoch 3:  47%|███████████████████▋                      | 8502/18177 [31:46<25:41,  6.28it/s, loss=2.5454, lr=4.09e-05]

Step 8500 | Loss 2.957


Epoch 3:  50%|████████████████████▊                     | 9002/18177 [33:32<22:50,  6.69it/s, loss=2.5558, lr=4.02e-05]

Step 9000 | Loss 3.180


Epoch 3:  52%|█████████████████████▉                    | 9502/18177 [35:26<24:46,  5.83it/s, loss=2.2171, lr=3.95e-05]

Step 9500 | Loss 2.438


Epoch 3:  55%|██████████████████████▌                  | 10000/18177 [37:18<20:16,  6.72it/s, loss=1.8636, lr=3.88e-05]

Step 10000 | Loss 1.864


Epoch 3:  55%|██████████████████████▌                  | 10002/18177 [37:18<27:59,  4.87it/s, loss=1.9836, lr=3.88e-05]

Saved checkpoint: full_sft_epoch3_step10000.pt


Epoch 3:  58%|███████████████████████▋                 | 10501/18177 [39:10<24:15,  5.27it/s, loss=3.2827, lr=3.81e-05]

Step 10500 | Loss 3.283


Epoch 3:  61%|████████████████████████▊                | 11002/18177 [41:02<17:36,  6.79it/s, loss=1.4995, lr=3.74e-05]

Step 11000 | Loss 2.026


Epoch 3:  63%|█████████████████████████▉               | 11502/18177 [42:56<28:52,  3.85it/s, loss=2.8738, lr=3.67e-05]

Step 11500 | Loss 4.110


Epoch 3:  66%|███████████████████████████              | 12002/18177 [44:50<22:49,  4.51it/s, loss=2.9231, lr=3.60e-05]

Step 12000 | Loss 3.495


Epoch 3:  69%|████████████████████████████▏            | 12502/18177 [46:41<16:26,  5.75it/s, loss=3.1855, lr=3.53e-05]

Step 12500 | Loss 4.180


Epoch 3:  72%|█████████████████████████████▎           | 13001/18177 [48:25<16:17,  5.29it/s, loss=3.5073, lr=3.47e-05]

Step 13000 | Loss 3.507


Epoch 3:  74%|██████████████████████████████▍          | 13502/18177 [50:17<11:51,  6.57it/s, loss=2.4625, lr=3.40e-05]

Step 13500 | Loss 2.134


Epoch 3:  77%|███████████████████████████████▌         | 14002/18177 [52:04<10:27,  6.65it/s, loss=2.6941, lr=3.33e-05]

Step 14000 | Loss 2.748


Epoch 3:  80%|████████████████████████████████▋        | 14502/18177 [54:03<08:39,  7.07it/s, loss=1.7658, lr=3.26e-05]

Step 14500 | Loss 2.913


Epoch 3:  83%|█████████████████████████████████▊       | 15001/18177 [55:50<09:35,  5.52it/s, loss=3.0395, lr=3.19e-05]

Step 15000 | Loss 3.040


Epoch 3:  85%|██████████████████████████████████▉      | 15502/18177 [57:45<07:05,  6.28it/s, loss=1.7389, lr=3.13e-05]

Step 15500 | Loss 2.965


Epoch 3:  88%|████████████████████████████████████     | 16002/18177 [59:35<05:50,  6.20it/s, loss=3.1437, lr=3.06e-05]

Step 16000 | Loss 1.405


Epoch 3:  91%|███████████████████████████████████▍   | 16502/18177 [1:01:24<07:51,  3.56it/s, loss=2.8672, lr=2.99e-05]

Step 16500 | Loss 2.373


Epoch 3:  94%|████████████████████████████████████▍  | 17002/18177 [1:03:18<03:46,  5.20it/s, loss=2.0931, lr=2.93e-05]

Step 17000 | Loss 2.973


Epoch 3:  96%|█████████████████████████████████████▌ | 17502/18177 [1:05:09<02:03,  5.47it/s, loss=2.3826, lr=2.86e-05]

Step 17500 | Loss 2.109


Epoch 3:  99%|██████████████████████████████████████▌| 18001/18177 [1:07:00<00:27,  6.52it/s, loss=1.9144, lr=2.79e-05]

Step 18000 | Loss 1.914


Epoch 3: 100%|███████████████████████████████████████| 18177/18177 [1:07:41<00:00,  4.48it/s, loss=2.7929, lr=2.77e-05]


Epoch 3 completed | Avg Loss: 2.6822 | Perplexity: 14.62


Epoch 4:   0%|                                           | 2/18177 [00:01<3:40:07,  1.38it/s, loss=1.6466, lr=2.77e-05]


GENERATION @ step 0
प्रश्न: स्वस्थ रहने के उपाय बताइए। ⁇ उत्तर: पहुंच और स्वास्थ्य के प्रति जागरूक होने से व्यक्ति और समुदाय के लिए अपने जीवन पर नियंत्रण और नियंत्रण की स्थिति में से एक हैं। अपने जीवन पर नियंत्रण और उचित स्वास्थ्य और सुरक्षा को प्राथमिकता देकर, व्यक्ति अपने स्वास्थ्य और कल्याण पर नियंत्रण की स्थिति में बेहतर महसूस कर सकते हैं। हालांकि, स्वस्थ स्वस्थ जीवन के लिए महत्वपूर्ण हैं। ⁇ सबसे पहले, अच्छे शारीरिक और मानसिक स्वास्थ्य को बनाए रखने में मदद करने

Step 0 | Loss 1.607


Epoch 4:   3%|█▏                                         | 502/18177 [01:51<59:00,  4.99it/s, loss=2.0569, lr=2.70e-05]

Step 500 | Loss 3.431


Epoch 4:   6%|██▏                                     | 1001/18177 [03:49<1:11:57,  3.98it/s, loss=1.9983, lr=2.64e-05]

Step 1000 | Loss 1.998


Epoch 4:   8%|███▎                                    | 1502/18177 [05:46<1:00:17,  4.61it/s, loss=2.8285, lr=2.57e-05]

Step 1500 | Loss 3.061


Epoch 4:  11%|████▍                                   | 2002/18177 [07:35<1:15:50,  3.55it/s, loss=2.4011, lr=2.51e-05]

Step 2000 | Loss 2.979


Epoch 4:  14%|█████▊                                    | 2501/18177 [09:30<43:30,  6.01it/s, loss=2.8714, lr=2.45e-05]

Step 2500 | Loss 2.871


Epoch 4:  17%|██████▉                                   | 3002/18177 [11:24<59:54,  4.22it/s, loss=2.4523, lr=2.38e-05]

Step 3000 | Loss 0.583


Epoch 4:  19%|████████                                  | 3502/18177 [13:19<39:39,  6.17it/s, loss=1.9062, lr=2.32e-05]

Step 3500 | Loss 3.051


Epoch 4:  22%|█████████▏                                | 4001/18177 [15:03<37:36,  6.28it/s, loss=1.9498, lr=2.26e-05]

Step 4000 | Loss 1.950


Epoch 4:  25%|██████████▍                               | 4502/18177 [16:54<42:41,  5.34it/s, loss=2.6961, lr=2.20e-05]

Step 4500 | Loss 2.665


Epoch 4:  28%|███████████▌                              | 5002/18177 [18:45<39:52,  5.51it/s, loss=2.2636, lr=2.14e-05]

Step 5000 | Loss 0.894


Epoch 4:  30%|████████████▋                             | 5502/18177 [20:36<30:00,  7.04it/s, loss=2.6938, lr=2.07e-05]

Step 5500 | Loss 1.817


Epoch 4:  33%|█████████████▊                            | 6002/18177 [22:34<37:56,  5.35it/s, loss=4.1786, lr=2.01e-05]

Step 6000 | Loss 2.387


Epoch 4:  36%|██████████████▎                         | 6501/18177 [24:22<1:20:53,  2.41it/s, loss=1.8516, lr=1.95e-05]

Step 6500 | Loss 1.852


Epoch 4:  39%|████████████████▏                         | 7001/18177 [26:13<41:07,  4.53it/s, loss=2.8597, lr=1.90e-05]

Step 7000 | Loss 2.860


Epoch 4:  41%|█████████████████▎                        | 7502/18177 [28:03<49:15,  3.61it/s, loss=3.5039, lr=1.84e-05]

Step 7500 | Loss 3.506


Epoch 4:  44%|██████████████████▍                       | 8001/18177 [29:53<39:39,  4.28it/s, loss=3.6541, lr=1.78e-05]

Step 8000 | Loss 3.654


Epoch 4:  47%|███████████████████▋                      | 8502/18177 [31:44<27:28,  5.87it/s, loss=2.6583, lr=1.72e-05]

Step 8500 | Loss 3.395


Epoch 4:  50%|████████████████████▊                     | 9002/18177 [33:32<24:37,  6.21it/s, loss=2.5047, lr=1.67e-05]

Step 9000 | Loss 3.226


Epoch 4:  52%|█████████████████████▉                    | 9501/18177 [35:29<47:58,  3.01it/s, loss=3.0611, lr=1.61e-05]

Step 9500 | Loss 3.061


Epoch 4:  55%|██████████████████████▌                  | 10000/18177 [37:19<23:50,  5.72it/s, loss=2.8785, lr=1.56e-05]

Step 10000 | Loss 2.878


Epoch 4:  55%|██████████████████████▌                  | 10001/18177 [37:19<34:05,  4.00it/s, loss=2.8785, lr=1.56e-05]

Saved checkpoint: full_sft_epoch4_step10000.pt


Epoch 4:  58%|███████████████████████▋                 | 10502/18177 [39:08<20:46,  6.16it/s, loss=1.9136, lr=1.50e-05]

Step 10500 | Loss 2.090


Epoch 4:  61%|████████████████████████▊                | 11002/18177 [40:54<20:26,  5.85it/s, loss=2.1529, lr=1.45e-05]

Step 11000 | Loss 2.405


Epoch 4:  63%|█████████████████████████▉               | 11501/18177 [42:46<19:41,  5.65it/s, loss=2.0900, lr=1.40e-05]

Step 11500 | Loss 2.090


Epoch 4:  66%|███████████████████████████              | 12002/18177 [44:38<14:18,  7.19it/s, loss=1.4256, lr=1.34e-05]

Step 12000 | Loss 2.636


Epoch 4:  69%|████████████████████████████▏            | 12502/18177 [46:32<16:31,  5.73it/s, loss=2.4255, lr=1.29e-05]

Step 12500 | Loss 3.075


Epoch 4:  72%|█████████████████████████████▎           | 13002/18177 [48:28<14:29,  5.95it/s, loss=2.8473, lr=1.24e-05]

Step 13000 | Loss 2.777


Epoch 4:  74%|██████████████████████████████▍          | 13502/18177 [50:27<13:11,  5.91it/s, loss=2.2035, lr=1.19e-05]

Step 13500 | Loss 2.507


Epoch 4:  77%|███████████████████████████████▌         | 14002/18177 [52:18<11:46,  5.91it/s, loss=1.7559, lr=1.14e-05]

Step 14000 | Loss 1.605


Epoch 4:  80%|████████████████████████████████▋        | 14502/18177 [54:04<10:15,  5.98it/s, loss=2.3034, lr=1.10e-05]

Step 14500 | Loss 2.465


Epoch 4:  83%|█████████████████████████████████▊       | 15001/18177 [55:53<07:33,  7.01it/s, loss=1.8899, lr=1.05e-05]

Step 15000 | Loss 2.600


Epoch 4:  85%|██████████████████████████████████▉      | 15502/18177 [57:42<07:21,  6.06it/s, loss=2.1897, lr=1.00e-05]

Step 15500 | Loss 3.770


Epoch 4:  88%|████████████████████████████████████     | 16002/18177 [59:37<12:47,  2.83it/s, loss=1.8348, lr=9.58e-06]

Step 16000 | Loss 2.949


Epoch 4:  91%|███████████████████████████████████▍   | 16502/18177 [1:01:29<07:56,  3.51it/s, loss=3.0019, lr=9.14e-06]

Step 16500 | Loss 1.527


Epoch 4:  94%|████████████████████████████████████▍  | 17002/18177 [1:03:21<05:06,  3.83it/s, loss=2.1485, lr=8.71e-06]

Step 17000 | Loss 2.737


Epoch 4:  96%|█████████████████████████████████████▌ | 17502/18177 [1:05:09<02:58,  3.77it/s, loss=2.5447, lr=8.29e-06]

Step 17500 | Loss 2.888


Epoch 4:  99%|██████████████████████████████████████▌| 18002/18177 [1:06:59<00:41,  4.18it/s, loss=1.6202, lr=7.87e-06]

Step 18000 | Loss 1.309


Epoch 4: 100%|███████████████████████████████████████| 18177/18177 [1:07:39<00:00,  4.48it/s, loss=2.9493, lr=7.73e-06]


Epoch 4 completed | Avg Loss: 2.4604 | Perplexity: 11.71


Epoch 5:   0%|                                           | 2/18177 [00:01<3:34:03,  1.42it/s, loss=2.2362, lr=7.73e-06]


GENERATION @ step 0
प्रश्न: स्वस्थ रहने के उपाय बताइए। ⁇ उत्तर: आपका हुए ए और बी हैं। आपको निम्नलिखित मात्रा को कम करने की आवश्यकता होगीः ⁇ ए और बी के बाद, आप सक्रिय रूप से अपनेa के साथ ए, बी और ए के लिए व्यायाम कर सकते हैं। अपने सामान्य लक्ष्य तक पहुंचने के लिए अपने शरीर को आवश्यक ऊर्जा प्रदान करने की आवश्यकता होती है। ⁇ एक ए के रूप में, आप अपने शरीर को ऊर्जा प्रदान करने के लिए अपने

Step 0 | Loss 3.027


Epoch 5:   3%|█▏                                         | 502/18177 [01:45<43:09,  6.82it/s, loss=2.7361, lr=7.33e-06]

Step 500 | Loss 3.172


Epoch 5:   6%|██▎                                       | 1002/18177 [03:36<44:14,  6.47it/s, loss=2.3444, lr=6.94e-06]

Step 1000 | Loss 2.793


Epoch 5:   8%|███▍                                      | 1502/18177 [05:28<38:12,  7.27it/s, loss=2.4478, lr=6.55e-06]

Step 1500 | Loss 2.037


Epoch 5:  11%|████▍                                   | 2002/18177 [07:26<1:05:44,  4.10it/s, loss=2.3530, lr=6.18e-06]

Step 2000 | Loss 2.630


Epoch 5:  14%|█████▌                                  | 2502/18177 [09:20<1:00:14,  4.34it/s, loss=1.6602, lr=5.82e-06]

Step 2500 | Loss 2.578


Epoch 5:  17%|██████▉                                   | 3001/18177 [11:16<38:52,  6.51it/s, loss=2.4291, lr=5.47e-06]

Step 3000 | Loss 2.429


Epoch 5:  19%|████████                                  | 3502/18177 [13:09<40:28,  6.04it/s, loss=3.1959, lr=5.13e-06]

Step 3500 | Loss 3.269


Epoch 5:  22%|█████████▏                                | 4002/18177 [15:06<42:53,  5.51it/s, loss=2.3077, lr=4.80e-06]

Step 4000 | Loss 1.888


Epoch 5:  25%|█████████▉                              | 4502/18177 [17:02<1:08:58,  3.30it/s, loss=2.6769, lr=4.48e-06]

Step 4500 | Loss 1.607


Epoch 5:  28%|███████████▌                              | 5002/18177 [18:56<41:11,  5.33it/s, loss=2.2488, lr=4.17e-06]

Step 5000 | Loss 2.902


Epoch 5:  30%|████████████▋                             | 5502/18177 [20:51<44:14,  4.78it/s, loss=2.3391, lr=3.87e-06]

Step 5500 | Loss 3.390


Epoch 5:  33%|█████████████▊                            | 6001/18177 [22:44<42:50,  4.74it/s, loss=2.6410, lr=3.59e-06]

Step 6000 | Loss 2.641


Epoch 5:  36%|███████████████                           | 6501/18177 [24:34<49:26,  3.94it/s, loss=2.7216, lr=3.31e-06]

Step 6500 | Loss 2.722


Epoch 5:  39%|████████████████▏                         | 7002/18177 [26:26<33:53,  5.50it/s, loss=3.0417, lr=3.04e-06]

Step 7000 | Loss 1.482


Epoch 5:  41%|█████████████████▎                        | 7502/18177 [28:19<29:48,  5.97it/s, loss=2.6115, lr=2.79e-06]

Step 7500 | Loss 2.580


Epoch 5:  44%|██████████████████▍                       | 8002/18177 [30:09<28:18,  5.99it/s, loss=2.1359, lr=2.55e-06]

Step 8000 | Loss 2.264


Epoch 5:  47%|███████████████████▋                      | 8502/18177 [32:01<22:14,  7.25it/s, loss=2.5474, lr=2.31e-06]

Step 8500 | Loss 3.112


Epoch 5:  50%|████████████████████▊                     | 9002/18177 [33:55<25:21,  6.03it/s, loss=1.9495, lr=2.09e-06]

Step 9000 | Loss 2.216


Epoch 5:  52%|█████████████████████▉                    | 9502/18177 [35:46<35:46,  4.04it/s, loss=2.6561, lr=1.88e-06]

Step 9500 | Loss 1.796


Epoch 5:  55%|██████████████████████▌                  | 10000/18177 [37:35<20:11,  6.75it/s, loss=2.8900, lr=1.68e-06]

Step 10000 | Loss 2.890


Epoch 5:  55%|██████████████████████▌                  | 10002/18177 [37:36<28:05,  4.85it/s, loss=2.5292, lr=1.68e-06]

Saved checkpoint: full_sft_epoch5_step10000.pt


Epoch 5:  58%|███████████████████████▋                 | 10502/18177 [39:29<18:42,  6.84it/s, loss=1.8709, lr=1.50e-06]

Step 10500 | Loss 2.190


Epoch 5:  61%|████████████████████████▊                | 11001/18177 [41:20<35:15,  3.39it/s, loss=1.8071, lr=1.32e-06]

Step 11000 | Loss 1.807


Epoch 5:  63%|█████████████████████████▉               | 11502/18177 [43:15<16:07,  6.90it/s, loss=2.4177, lr=1.16e-06]

Step 11500 | Loss 2.499


Epoch 5:  66%|███████████████████████████              | 12002/18177 [45:04<17:07,  6.01it/s, loss=2.9846, lr=1.01e-06]

Step 12000 | Loss 2.267


Epoch 5:  69%|████████████████████████████▏            | 12502/18177 [46:57<24:36,  3.84it/s, loss=2.2624, lr=8.66e-07]

Step 12500 | Loss 1.757


Epoch 5:  72%|█████████████████████████████▎           | 13002/18177 [48:54<13:19,  6.47it/s, loss=2.9594, lr=7.37e-07]

Step 13000 | Loss 2.074


Epoch 5:  74%|██████████████████████████████▍          | 13501/18177 [50:38<12:51,  6.06it/s, loss=2.9931, lr=6.21e-07]

Step 13500 | Loss 2.993


Epoch 5:  77%|███████████████████████████████▌         | 14001/18177 [52:24<21:53,  3.18it/s, loss=1.5795, lr=5.15e-07]

Step 14000 | Loss 2.613


Epoch 5:  80%|████████████████████████████████▋        | 14502/18177 [54:04<14:16,  4.29it/s, loss=2.2520, lr=4.22e-07]

Step 14500 | Loss 2.528


Epoch 5:  83%|█████████████████████████████████▊       | 15001/18177 [55:55<12:24,  4.26it/s, loss=2.3196, lr=3.40e-07]

Step 15000 | Loss 3.252


Epoch 5:  85%|██████████████████████████████████▉      | 15501/18177 [57:52<06:34,  6.78it/s, loss=2.6754, lr=2.71e-07]

Step 15500 | Loss 2.675


Epoch 5:  88%|████████████████████████████████████     | 16002/18177 [59:34<07:15,  5.00it/s, loss=2.1533, lr=2.13e-07]

Step 16000 | Loss 2.345


Epoch 5:  91%|███████████████████████████████████▍   | 16501/18177 [1:01:27<04:00,  6.97it/s, loss=2.5080, lr=1.67e-07]

Step 16500 | Loss 2.508


Epoch 5:  94%|████████████████████████████████████▍  | 17002/18177 [1:03:23<03:06,  6.31it/s, loss=2.5648, lr=1.33e-07]

Step 17000 | Loss 2.905


Epoch 5:  96%|█████████████████████████████████████▌ | 17502/18177 [1:05:12<01:53,  5.93it/s, loss=1.7115, lr=1.11e-07]

Step 17500 | Loss 1.735


Epoch 5:  99%|██████████████████████████████████████▌| 18002/18177 [1:07:03<00:41,  4.24it/s, loss=2.9351, lr=1.01e-07]

Step 18000 | Loss 1.740


Epoch 5: 100%|███████████████████████████████████████| 18177/18177 [1:07:43<00:00,  4.47it/s, loss=2.1609, lr=1.00e-07]


Epoch 5 completed | Avg Loss: 2.3018 | Perplexity: 9.99
Full SFT complete! Final model saved as: full_sft_final.pt
